# fly.toml app configuration file generated for genibook-backend-winter-frost-9064-solitary-voice-9775 on 2024-02-10T12:51:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'genibook-backend'
primary_region = 'iad'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[env]
  PORT = '6969'

[http_service]
  internal_port = 6969
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
